### ISSUE TITLE
LinkedIn deprecates use of v1 APIs since May 1, 2019

### ISSUE THREAD

**Issue by arvindpdmn** [Joomline/slogin#102]
See this note on Microsoft Docs site: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context

Currently, login via LinkedIn fails. I get this error:
```
{
    "errorCode": 0,
    "message": "This resource is no longer available under v1 APIs",
    "requestId": "somestring",
    "status": 410,
    "timestamp": 1558008912595
}
```

**Comment by zikkuratvk** [comment]
Hello, this social network is not available for us, the LinkedIn site is blocked. We cannot do normal debugging work. If you have a ready-made solution, we will take PR.
