### ISSUE TITLE
Кастомизация кнопок модуля slogin

### ISSUE THREAD

**Issue by Sulpher** [Joomline/slogin#113]
К сожалению, в модуле нельзя кастомно прописать стиль для кнопок. идет привязка к существующим классам.

Скриншот как выводится и как хочу вывести (Uikit):
![Screen Shot 2020-05-25 at 18 41 22](https://user-images.githubusercontent.com/3432048/82827458-c1738a80-9eb7-11ea-8e6d-9cc9ac730b49.png)

Собственно, оформление кнопки Uikit:

`<a href="" class="uk-button uk-button-primary uk-width-1-1 uk-margin-small-bottom"><span uk-icon="icon: facebook"></span> Facebook</a><br />`

А вот какой код slogin модуля, выводящий кнопки:

`    <?php if (count($plugins)): ?>
    <?php
        foreach($plugins as $link):
            $linkParams = '';
            if(isset($link['params'])){
                foreach($link['params'] as $k => $v){
                    $linkParams .= ' ' . $k . '="' . $v . '"';
                }
            }
			$title = (!empty($link['plugin_title'])) ? ' title="'.$link['plugin_title'].'"' : '';
            ?>
            <a  rel="nofollow" class="link<?php echo $link['class'];?>" <?php echo $linkParams.$title;?> href="<?php echo JRoute::_($link['link']);?>"><span class="<?php echo $link['class'];?> slogin-ico">&nbsp;</span><span class="text-socbtn"><?php echo $link['plugin_title'];?></span></a>
        <?php endforeach; ?>
    <?php endif; ?>`

Классы такие: facebookslogin и т.д. Это тянется из недр компонента.
Предлагаю переделать классы для соответствия Uikit - тогда будет легко кастомизировать.

**Comment by Sulpher** [comment]
Сделал по хардкору.
Просто убрал цикл и вставил HTML код с URLs. нужно просто следить будет, если понадобится что-то еще добавить.

**Comment by zikkuratvk** [comment]
Проблема данного подхода, что решение не универсально. Компонент должен работать и на сайте BS и UIKIT и вообще без фреймворка.

**Comment by Sulpher** [comment]
Можно ли хотя бы опцию в модуле сделать "подключать css стили"? и по умолчанию включать. для большинства юзеров это подойдет, а в моем случае, наоборот, стандартные стили не нужны, т.к. переделал  вывод на базе Uikit3 и лишние файлы лучше отключать.

**Comment by zikkuratvk** [comment]
![image](https://user-images.githubusercontent.com/2261206/82832998-1665cf80-9ebd-11ea-83f8-3d03cb08a987.png)
опция отключения JS и CSS давно имеется.

**Comment by Sulpher** [comment]
упс, не заметил... :-) спасибо.
