### ISSUE TITLE
Электронная почта не прошла проверку или устаревшая API Facebook в коде плагина

### ISSUE THREAD

**Issue by Sulpher** [Joomline/slogin#120]
Обнаружил, что не получается авторизоваться на сайте. получаю ошибку:

Электронная почта не прошла проверку

Гугл подсказал этот топик:
https://joomline.net/forum/slogin/6052-error-empty-access-tocken.html#6626
здесь человек указывает на устаревший API  в коде плагина facebook.php.

посмотрел на сайте (версия компонента - 2.10.0)

```
            $ResponseUrl = 'https://graph.facebook.com/v2.12/me?access_token='.$token['access_token'].'&fields=id,name,first_name,last_name,link,email';
            $request = json_decode($controller->open_http($ResponseUrl));

```

смотрю приложение FB. там уже минимум - 7.0.
<img width="1032" alt="Снимок экрана 2021-08-24 в 11 09 18" src="https://user-images.githubusercontent.com/3432048/130581826-3c628f92-6b4d-4dd8-b22e-4c3f98d1904f.png">

https://github.com/Joomline/slogin/blob/2.10.0/plugins/slogin_auth/facebook/facebook.php

попробовал в коде заменить 2.12 на 7.0 - эффекта не дало.

**Comment by zikkuratvk** [comment]
Обновил до 13 версии сразу 1833650fdb1e110b9458b4ee48fa3e41e6425481
