### ISSUE TITLE
Поддержка Joomla v4

### ISSUE THREAD

**Issue by kolkov** [Joomline/slogin#121]
Приветствую!
Будет ли плагин работать на версии 4? Чекер предупреждает...

![image](https://user-images.githubusercontent.com/3740898/151779540-d865127a-b1f7-4aee-9e82-b36c06299ff6.png)

С наилучшими!

**Comment by zikkuratvk** [comment]
Нет не будет пока мы не знаем когда появится версия под Joomla 4.

**Comment by zikkuratvk** [comment]
В релизе 3.0.0 реализована поддержка Joomla 4.
