### ISSUE TITLE
При авторизации через Joomla 3 невозможно завершить регистрацию.

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#123]
Если выставить вот такие настройки:
![image](https://user-images.githubusercontent.com/2261206/186372551-85605ee2-866f-4200-a234-d765a4ffc690.png)

То невозможно завершить регистрацию полностью новым пользователем.

Доходим вот до этого шага: 
![image](https://user-images.githubusercontent.com/2261206/186372853-0bd44b73-64ac-4bc9-9f22-e18e698c1e13.png)

И при клике на кнопку отправить страница просто перезагружается.

**Comment by Ulfhednur** [comment]
> И при клике на кнопку отправить страница просто перезагружается.
341 строка, если я не ошибаюсь.
JForm::addFormPath(JPATH_ROOT. '/components/com_users/forms'); 
поменять на
JForm::addFormPath(JPATH_ROOT. '/components/com_users/models/forms');
Это если костылить специально под J3
если по уму - сейчас попробую пул реквест сделать...
