### ISSUE TITLE
кроппинг аватаров

### ISSUE THREAD

**Issue by Sulpher** [Joomline/slogin#46]
предлагаю предусмотреть кроппинг аватаров. сейчас вытягивает по ширине. например, в твиттере аватарка квадратная - пропорциональная, на сайт вписывается красиво,
а авторизовываюсь под FB - там прямоугольная аватарка (по высоте больше)
некрасиво. было бы здорово предусмотреть кроппинг аватарок.

**Comment by Arkadiy-Sedelnikov** [comment]
Автоматический кроппинг чреват обрезкой нужных деталей. Легче все это в css по своему вкусу настроить.
