### ISSUE TITLE
Доработка слияния аккаунтов

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#59]
Добавить опцию при которой указанная группа пользователей, сливает аккаунт автоматически, если е-меил совпадает.

Как это работает.
Пользователь зарегистрирован уже на сайте. 
Под каким либо е-меилом. 
Нажимает на авторизацию через социальную сеть.
Если в профиле социальной сети и аккаунте сайт е-меил совпадает, то происходит слияние аккаунтов и авторизация, автоматически, без дополнительных окон.

В чем плюс такой системы?
Е-меил уже проверяется социальной сетью.
Отсутствие дополнительных окон.
Быстрота.
Может использовать для восстановления доступа к аккаунту, если пользователь забыл пароль.

У нас есть уже опция авторизация без запроса каких либо данных, но если е-меил совпадает, происходит создание почты такого формата mail-1@mail.ru
Предлагаю расширить эту настройку и добавить опцию автоматического слияния аккаунта.

**Comment by Arkadiy-Sedelnikov** [comment]
Не пойдет, возникнет дыра, позволяющая авторизоваться другим пользователем. Конечно надо знать емайл, но факт остается фактом.
