### ISSUE TITLE
Авторизация в твиттер ие 11

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#60]
При авторизации в тивиттер ошибка  "Remote authorization not allowed". Происходит только в ие 11, в остальных браузерах происходит авторизация нормально. Воспроизводится на сайте http://mc-class.ru/.

http://prntscr.com/6tzvzg

**Comment by Arkadiy-Sedelnikov** [comment]
0b0a878bd080b59b3045be7c27299dd71f53f02e
