### ISSUE TITLE
Ошибка "Error - empty code" при отмене авторизации

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#64]
Как воспроизвести:

Заходим на страницу: http://demo17.joomline.ru/slogin.html

Выбираем авторизацию (подвержены все сети) но тестировал на Twitter.

На запрос об предоставлении данных в сети твиттер нажимаем "Отмена" 

В окне информационном на запрос "Вы не вошли в demo17" щелкаем "Вернуться к demo17", и получаем вот такое окно https://yadi.sk/i/mq2FKgZUi2Nph

**Comment by Arkadiy-Sedelnikov** [comment]
А есть смысл с этим заморачиваться? Отказы у нас нигде не обрабатываются, по моему легче окно закрыть сразу чем отмены нажимать.

**Comment by Arkadiy-Sedelnikov** [comment]
1b1e2af28a0d11930c44c66edbf11b4c5ae49daa
