### ISSUE TITLE
Проблема со сбросом кеша при авторизации Slogin

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#66]
описание проблемы на форуме

http://joomline.net/ru/forum/slogin/5672-sbros-kesha-pri-logine.html

**Comment by Arkadiy-Sedelnikov** [comment]
SLogin не сбрасывает кэш, более того, он не авторизует пользователей, а только подготавливает данные для авторизации. Саму авторизацию делает joomla тем же самым методом, что и при обычном логине.
