### ISSUE TITLE
проблема авторизации через Live.com

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#67]
При авторизации через live.com происходит ошибка

**Comment by drinkmaker** [comment]
Подтверждаю, у меня такая же ботва.
Мало того, в Joomla 3.4.8 в файле /plugins/slogin_auth/live/element/callbackurl.php нужно поправить подключение роутера и апликейшн. Правильно так:

require_once (JPATH_ROOT . '/libraries/cms/router/site.php');
require_once(JPATH_SITE .'/libraries/cms/application/site.php');
