### ISSUE TITLE
Social Network login button not showing on joomla 3.5

### ISSUE THREAD

**Issue by yozawiratama** [Joomline/slogin#72]
i've followed all instruction, but social login button not show.
may be there is connection with joomla 3.5 update code? like captcha not show in joomle 3.5

**Comment by Arkadiy-Sedelnikov** [comment]
You have installed the module Slogin, published it and assigned him the position of the template?

**Comment by yozawiratama** [comment]
Ok, thanks for solution, i dont know if i must select page to show.
