### ISSUE TITLE
При удалении компонента Slogin рушится сайт

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#75]
Если мы удаляем компонент Slogin а все остальные плагины при этом остаются, то мы получаем ошибку на всем сайте:
Fatal error: require_once(): Failed opening required '/www/components/com_slogin/helpers/password.php' (include_path='.:/usr/local/php/php-5.5/lib/php') in /www/plugins/authentication/slogin/slogin.php on line14

**Comment by zikkuratvk** [comment]
предлагаю добавить обработку в плагин аутентификации.

**Comment by Arkadiy-Sedelnikov** [comment]
7ed83d6c1aa357695120dfe7c9dd54fefcc8c1ee
