### ISSUE TITLE
Кнопки слияния аккаунта в модуле

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#78]
поступило предложение сделать кнопки слияния аккаунта не на отдельной странице, а в модуле авторизации.
В чем плюс: 
Можно выводить в профиле пользователя.
Можно использовать чтоб пользователь видел через какую соц сеть авторизоваля, и какие сети у него уже к аккаунту привязаны... Пользователь не всегд понимает что есть такие функции.

**Comment by viocassel** [comment]
Поддерживаю данную идею!

**Comment by Ilya-Zhulin** [comment]
А я еще больше ку!

**Comment by Arkadiy-Sedelnikov** [comment]
Ок, сделаем в следующем релизе.

**Comment by addept** [comment]
Поддерживаю! Отличная идея

**Comment by Ilya-Zhulin** [comment]
А примерный срок можно? Уж очень надо.

**Comment by Arkadiy-Sedelnikov** [comment]
eab61ca0f0ba39a60b3fb1c893cff4c1ed74ecb1
