### ISSUE TITLE
Таблицы sql

### ISSUE THREAD

**Issue by kolkov** [Joomline/slogin#79]
Есть 2 таблицы:
```
_slogin_users
_plg_slogin_profile
```
первая - точная копия первой части второй таблицы.
Какой в этом смысл? Не проще ли использовать только вторую? 
С чем это связано? Или я чего-то не понимаю...?

**Comment by Arkadiy-Sedelnikov** [comment]
Первая таблица от компонента, вторая от плагина профиля, плагин профиля может быть не установлен.

**Comment by kolkov** [comment]
Не представляю ситуации когда он не установится, но я Вас услышал.

**Comment by zikkuratvk** [comment]
К сожалению такие ситуации бывают, что устанавливают не весь пакет а скажем по частям,  так же удаляют по частям, в том числе и только плагин профиля. Не скажу что это большой процент, но даже если из 1000, 10 человек сделает не так, как все, это уже может вызвать небольшой калапс.
