### ISSUE TITLE
Проблема при объединении профиля через модуль

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#80]
Механизм сам работат отлично, за исключением одной проблемы.
При слиянии/отвязки профиля через модуль идет редирект на страницу слияния профилей Slogin.

По логике вещей пользователь вообще туда не должен попадать при таком механизме, а оставаться на той же странице, где он начал процедуру слияния.

**Comment by Arkadiy-Sedelnikov** [comment]
4aa136785fcb5cf31010c16825935833b5e1d1b5
