### ISSUE TITLE
Проблема с подпапками домена

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#86]
Проблема с авторизацией у сайта находящегося в подпапке.

http://joomline.net/ru/forum/slogin/5975.html

**Comment by Arkadiy-Sedelnikov** [comment]
И ты туда-же :) зачем люди устанавливают джумлу в подпапке?

**Comment by zikkuratvk** [comment]
Не знаю, но таких товарищей много :-)

**Comment by zikkuratvk** [comment]
решено
