### ISSUE TITLE
Ошибка при авторизации FB

### ISSUE THREAD

**Issue by Aserus** [Joomline/slogin#87]
если на сайте будет включены все ошибки то юзер скорей всего увидет ошибку с 82 строкой (вроде как ФБ не возвращает теперь expires)

![2017-03-29 17 05 16](https://cloud.githubusercontent.com/assets/10893615/24461143/f152b6d2-14a8-11e7-8d1d-33d9c72afd0c.png)

**Comment by Arkadiy-Sedelnikov** [comment]
Спасибо, не заметил.
