### ISSUE TITLE
Facebook login fails

### ISSUE THREAD

**Issue by arvindpdmn** [Joomline/slogin#88]
This used to work before but today it is failing. Not sure if there's a setup issue on server or something's changed at FB. Slogin says `Error - empty access tocken`

Any help is much appreciated.

I looked at the HTTP calls (xxx to hide details):

`
https://xxx.org/component/slogin/provider/facebook/auth
HTTP/1.1 302 Moved Temporarily

https://www.facebook.com/dialog/oauth?client_id=xxx&redirect_uri=https://xxx.org/?option=com_slogin&task=check&plugin=facebook&scope=email,user_photos,user_about_me,user_hometown,public_profile,user_birthday&response_type=code
HTTP/2.0 302 Found

https://xxx.org/?option=com_slogin&task=check&plugin=facebook&code=AQBYQ5yEGrAB-HYUieFShGBa7A3JEisPdMxYbjYQ1lL-B9sHM_2gyc46VMoO_TD4FquduoEPM0G9YsSFBmfLY8gqu9ddu5za4JBsSG63Thkca4dOVWAvNHijckNZxYTckW2YB9eJyS6OQKU30Du1wSXGDIHEfs5L1aFUtOoVEzHUPW7-4nsgCfl0RgMc8JKfW0_qsHjJBNSnGjhpWMfR887Tj-m9y1pHbJr-mFA7UXcMWNSLZ5-AjgywMM1q-tjMXV5HGYybB-Zpzv3gjKuvRBfBBrIgzUNljIf7HtgkF5dZKeK-5hYagn3h4Ya2KpxbUCk#_=_
HTTP/1.1 200 OK
`

**Comment by arvindpdmn** [comment]
Okay, I found the issue. FB is returning JSON instead of query string. Looks like latest version already has the fix.  `parse_str($data, $data_array);` changed to `$data_array = json_decode($data,true);`

**Comment by Arkadiy-Sedelnikov** [comment]
Hello. this issue is resolved. download the repository and replace the files of the plugin authorize Facebook.
