### ISSUE TITLE
Добавить поддержку кастомных полей

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#91]
Добавить настройки позволяющие сохранять данные в кастомные поля Joomla

**Comment by Arkadiy-Sedelnikov** [comment]
Поподробнее пожалуйста :)

**Comment by zikkuratvk** [comment]
Предлагаю создать плагин интеграции с полями Joomla. Где можно будет указать id Поле в которое сохранять данные из плагина.
Допустим я хочу сделать профиль на полях Joomla на основе контактов.
Создаю поля:
Аватар.
Дата рождения.
Ссылка на профиль.

Указываю id Поля в настройках плагина и он туда сразу дублирует информацию при авторизации человека.

**Comment by Arkadiy-Sedelnikov** [comment]
Нам ведь еще как-то надо учитывать тип поля, просто скорее всего только текстовые поля могут получиться.

**Comment by zikkuratvk** [comment]
Ну аватар наверное в поле картинки должен быть, а все остальное текстовые поля.

**Comment by Arkadiy-Sedelnikov** [comment]
43eea44b353551c22852c7ebde6af41de7dde44e
