### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Brightside56** [Joomline/slogin#92]
Привет. Насколько реально появление поддержки Discord в компоненте?

https://discordapp.com/
https://discordapp.com/developers/docs/topics/oauth2

Готов пожертвовать адекватную сумму для появления этой нужной мне фичи

**Comment by zikkuratvk** [comment]
Здравствуйте, если вы готовы потратить тысячи 4 на реализацию этого провайдера то сделаем.

**Comment by Brightside56** [comment]
@zikkuratvk , как с вами связаться?

**Comment by zikkuratvk** [comment]
sale@joomline.ru
