### ISSUE TITLE
Проблема с полями полями Joomla

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/slogin#93]
В 2.6 появились поля, но проблема в том что у многих еще Joomla ниже 3.7 и это вызывает ошибку. Надо наверное обработку в плагин профиля добавить.

**Comment by Arkadiy-Sedelnikov** [comment]
Не, надо установить ограничение на установку начиная с 3.7.

**Comment by zikkuratvk** [comment]
ну в целом тоже верно))

**Comment by Septdir** [comment]
Надо ставить ограничение на joomla 3.8 и заодно переписать на namespaces тогда с j4 останется меньше работы
