### ISSUE TITLE
helper require

### ISSUE THREAD

**Issue by znay-ka** [Joomline/slogin#97]
Парни, подскажите, в чём прикол:
На строке
https://github.com/Joomline/slogin/blob/11c800620975a2a75157c0254b2130e972d1be77/mod_slogin/helper.php#L14
вызывается '/components/com_slogin/helpers/providers.php'
хотя фактически файл лежит в 
.../com_slogin/site/helpers/providers.php
т.е. в директории site

**Comment by Arkadiy-Sedelnikov** [comment]
Директория site существует только в дистрибутиве.
