### ISSUE TITLE
Twitch plugin

### ISSUE THREAD

**Issue by neo191987** [Joomline/slogin#98]
Hello, I made a Twitch plugin for your component. If you want, you can add it to your component. I'll write a few more plugins that I need.

[twitch.zip](https://github.com/Joomline/slogin/files/2663740/twitch.zip)

**Comment by zikkuratvk** [comment]
Hi
Tested your plugin.
Everything is good. We will include the plugin in the next release, now we are preparing the release.

**Comment by zikkuratvk** [comment]
b73d539104165dd4df1ab9e4ae0298e5971b6cf6
